### ISSUE TITLE
Casting teleother on another player causes a new fight to be recorded

### ISSUE THREAD

**Issue by Nightfirecat** [Matsyir/pvp-performance-tracker#14]

**Comment by Matsyir** [comment]
I could understand what happened when looking at the code, but this was tricky to reproduce, since there's a big delay for attacking stuff after tb (maybe that is ignored if you were already in combat? or maybe it waits for their response? I'm not sure). I ended up reproducing it by just following a player and then attacking something, since it's the same thing in terms of events fired. I'm about to test a fix that will verify that what you're attacking is the initial player you targeted, which would cause a 'fight' caused by a simple tb to never be saved since there'll be 0 attacks.

I can fully envision coming across this with follow or trade, but how the hell did you find this with teleother? Just curious at this point lol - I see the problem.

**Comment by Nightfirecat** [comment]
I ran into it when I was training on sand crabs and used Teleother Falador on a bot to interrupt them. Glad you were able to track it down though

**Comment by Matsyir** [comment]
Fair enough! Fairly unusual case but annoying if it happens. I saw this problem before (not with teleother though), couldn't think of a fix at the time, but it turned out to be pretty straightforward after thinking it through some more.
