### ISSUE TITLE
Magic Luck Calculation

### ISSUE THREAD

**Issue by Matt12yearslater** [Matsyir/pvp-performance-tracker#17]
**Related plugin component(s)**
Magic luck, deserved catches

**Describe the bug**
Not sure if it is a bug, incorrect equation, missing factors, or just bad luck, but after testing on multiple accounts strictly in LMS, average magic luck appears to consistently trend toward unlucky (< 100%) rather than average (100%). Normally seems to balance out around 90 - 95% over a few thousand fights.

**To reproduce**
Difficult to reproduce without thousands of test runs, could send tracker data and to confirm you could possibly ask for tracker data from other users to confirm legitimacy of issue.

**Expected behavior**

**Screenshots**
If applicable, add screenshots or clips to help explain your problem.

**Additional context**
Add any other context about the problem here. Logs could be useful if it is a severe problem.

**Comment by Matsyir** [comment]
This is likely due to the fact that the "deserved catches" statistic assumes that you always use Augury while maging, while in reality this might not be the case. Unless consistently hitting all offensives correctly, this seems normal to me.

The reason it works like this is because we can't detect which offensive prayer the opponent is using. The statistic wouldn't be "fair" if it took _your_ offensive prays into account, but not the opponent's. It would give an advantage to either player, depending how it was done.

This shouldn't be an issue with merged/analyzed fights, or if you both used augury for 100% of mage casts.

**Comment by Matsyir** [comment]
I've made a slight edit to the _Stat 4: Magic Hits_ section of the wiki to clarify this. It wasn't very clear, to be fair.
