### ISSUE TITLE
Plugin panel shows "CHECK CONFIG - NOT SETUP!"

### ISSUE THREAD

**Issue by Nightfirecat** [Matsyir/pvp-performance-tracker#19]
It doesn't explain what that means or how to resolve it

----------
**QUICK FIX: Go to the plugin's config, and enable the "I have verified my settings" config option. This will remove the warning label.**

**Comment by Matsyir** [comment]
There should be a tooltip on the red label that says "Please verify that the plugin is configured according to your needs".

The intent of this was to have people at least _acknowledge_ that a config for the plugin exists, since many users didn't even realize that beforehand (and probably still don't). The first config option is a checkbox called "I have verified my settings", and all that does is hide that label/warning. But it's really just there to force people to navigate to the config at least once, so they know it exists. That config also includes more details in the tooltip. Depending how you're using the plugin, the config can have a pretty big effect on results, so I think it's good for people to know about it, especially if they're pking with unusual setups where they would benefit from updating the level/gear/ammo configs accordingly. It's intentionally a little unclear/not "guided" because the intent isn't to have users quickly turn off that warning, it's to have users actually read the config and have them acknowledge that they "have verified settings (configuration)". Even if they didn't verify the settings, at least they know they exist now.

Let me know what you think.. I understand it's not ideal but I'd like to keep the feature. There isn't much space to work with, and since the target audience is people who _don't_ know about configs, I'm not sure being more specific will help much.

I would have liked to make it a button instead of a label, which when clicked opens the configuration panel, but I couldn't get that to work. I'd also keep a config option as a right click option on the entire "Total Stats Panel", if I could get that working.

**Comment by Nightfirecat** [comment]
You should be able to use a similar approach to how overlays are able to open config panels to achieve the same result by clicking on that label/button from this plugin's panel. As it is, it's not fully clear how to resolve the issue without noticing the tooltip--I don't remember having noticed it prior to you having mentioned it here.

**Comment by Matsyir** [comment]
Do you know of any plugins that do this? I've tried "following" the overlay right click menu behavior to do this in the past, and again now, and it doesn't seem possible since it's using custom menu entries which I don't have access to. For the overlay, they seem to be custom menu entries, similar to the actual games', which have been injected for overlays specifically. I might be missing something but it doesn't seem accessible. I also tried to replicate how the "config" button works, on the list of plugin hub plugins, but that was similar, it's actually built aside the config "plugin" so it's using even more direct stuff I don't have access to.

**Comment by Nightfirecat** [comment]
I did see your Discord messages. Maybe in lieu of opening the config panel, this could be a more descriptive message. "Check plugin config for setup options" or something of the sort?

**Comment by Matsyir** [comment]
I submitted that exact new text as an update, tried to think of a few other ways but couldn't really think of anything better that fit. Also slightly updated the tooltips. I've started making UI for "tabs" to allow for a custom config to further address this. I'll also try and make a concise "information" tab to have a quick explanation of all the features/configs. I'll close for now. I've edited a quick fix into your initial post in case any other confused users happen to come across this issue.
