### ISSUE TITLE
Viggora's chain mace not detected as an attack

### ISSUE THREAD

**Issue by pwatts6060** [Matsyir/pvp-performance-tracker#31]
**Describe the bug**
If you're being attacked by someone with viggora's chainmace, the tracker doesn't log them as attacks. I fought with a guy using rune cbow and viggora's and it only logged the range hits.
![image](https://user-images.githubusercontent.com/30028569/186538577-69519d58-4b63-40ad-b709-52d75a3b5531.png)

**Comment by Matsyir** [comment]
Fixed by commit 5672af35163f28c8fd428e751956f67f9846ad16 (awhile ago but was never fully sent to be released as an update), should be live tonight or within the next few days. Sorry about the massive delay on this one but I didn't think it was too high priority which is why I didn't feel the need to release that update as an update by itself.
