### ISSUE TITLE
issue with pvp performance tracker

### ISSUE THREAD

**Issue by SassanechTTV** [Matsyir/pvp-performance-tracker#38]
**Related plugin component(s)**
Statistic #2: Deserved Damage, Fight Log Window

**Describe the bug**
A clear and concise description of what the bug is.  names were originally loading incorrectly was not factoring in fights but would show " fights "of the same person it didn't happen. now the plugin not working at all

**To reproduce**
1. Go to rune lite, launch runelite and the plug in is unavailable
2. Attack while using any combat style or weapon 
4. Observe unexpected behavior the plug in no longer there tried removing and is unavailable. not loading at all'

**Expected behavior**
the app to load on runelite, show statistics from fights and show information in chat as well
**Screenshots**
[If applicable, add screenshots or clips to help explain your problem.] (https://prnt.sc/2junR60P9vBW)

**Additional context**
this has happened for two days in a row the plug in is not available to me and it won't appear, unable to remove and re-add.

**Comment by Matsyir** [comment]
The plugin is intentionally marked as unavailable for the time being, it's broken due to issue #37 - you can click that link to follow updates on the issue being resolved. If it were made available, it wouldn't be working and would just unnecessarily pollute your existing fight data, and may cause lag.
